### ISSUE TITLE
Apply design from Figma to SelectContent component in Select

### ISSUE THREAD

**Issue by kanta1207** [nishiki-tech/nishiki-frontend#127]
## Description

The task is to apply the design for the `SelectContent` component defined in Figma. The size, icon, and color may be currently different from the given design.

## Screen Captures

<img src="https://github.com/genesis-tech-tribe/nishiki-frontend/assets/99148565/1864ba74-08e1-43ad-9183-67e820d2a028" width="400" />

## Notes

- Please find the styles in the [Figma](https://www.figma.com/file/m0DaNrd0yXWbY4Dy7cuZiN/Nishiki-project?type=design&node-id=0%3A1&mode=design&t=XasBccR87Fnwdj9B-1). You may also need to download the SVG icon from the Figma design.

**Comment by AnukratiMehta** [comment]
@nick-y-ito 

Hello, please assign this to me. Thanks!

**Comment by nick-y-ito** [comment]
@AnukratiMehta 
We would really appreciate it if you could address this issue as well. Thank you so much for your help!

You can find the SVG file at:
```
src/assets/images/icons/icon_check.svg
```
