### ISSUE TITLE
Change the  colors of the Calendar component

### ISSUE THREAD

**Issue by nick-y-ito** [nishiki-tech/nishiki-frontend#136]
## Description

Apply the primary color to the Calendar component.

## Criteria

- [ ] Replace the grayish bg color for a selected date with the `bg-primary` color with `text-white`

## Notes

- [Discord Chat](https://discord.com/channels/1154534169796431873/1156355812395077643/1188627297377464351) in which the designer suggested about the style

**Comment by AnukratiMehta** [comment]
Hello, I would like to give this a try, please.

**Comment by nick-y-ito** [comment]
@AnukratiMehta 
Please give it a try! Although the design is not specified, this task should be much easier.
