### ISSUE TITLE
"Rename container" feature in Group single page

### ISSUE THREAD

**Issue by kanta1207** [nishiki-tech/nishiki-frontend#201]
## Description
`Rename a container` feature in Group single page
This issue will be addressed after implementing Popover component in #192

![image](https://github.com/nishiki-tech/nishiki-frontend/assets/142355969/47c03e4a-e684-4002-bbc1-9a4d3b090fdf)

## Tasks
- [x] #285 
- [x] #289

**Comment by ShoeheyOt** [comment]
I will close this issue because all the children of this issue is implemented. Thank you all for reviewing!
