### ISSUE TITLE
Adjust the position of the close [ x ] button of the Dialog component

### ISSUE THREAD

**Issue by nick-y-ito** [nishiki-tech/nishiki-frontend#229]
## Description

The cross button should be aligned to the center line of the header.

## Criteria

- [ ] Move the cross button into the `DialogHeader`
- [ ] Align the contents of the header to the center line, as instructed in the image.

## Screen Captures

<img src="https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/9bd8de30-dabc-404c-9766-c9d689259713" width="400" />

## Notes

- The component structure and styles of `DrawerHeader` in `src/components/ui/Drawer.tsx` should be similar.
- To inspect the style, you can refer to `src/components/ui/DrawerUsageExample.tsx`.

**Comment by AnukratiMehta** [comment]
Hello, I would like to work on this.

**Comment by nick-y-ito** [comment]
@AnukratiMehta 

Thank you for showing interest in the Nishiki project! We are thrilled to have your support in addressing the issue.

As per your request, I have added some notes in the project description that should assist you in tackling the problem. Please let me know if you require any further assistance or clarification.
