### ISSUE TITLE
Remove the unwanted input fields on the login page

### ISSUE THREAD

**Issue by kotaaaa** [nishiki-tech/nishiki-frontend#236]
## Description

The task is, on the login page, to remove the unwanted username and password fields, which are automatically generated by Amplify UI.

## Criteria

- [x] Remove the username and password form at the login page and adjust the design
- [x] Add loading spinner

## Notes

-

## Screen Captures

<img src="https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/573b7a57-2c30-415e-b048-e2c11a173056" width="500" />

**Comment by nick-y-ito** [comment]
## Without account selection

https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/56f12722-8d95-4b3e-a33c-63664868c6d6


## With account selection

https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/1271b894-d178-4d86-9343-2f905ea50e2a
