### ISSUE TITLE
Implement "Delete account" API client and apply it to Profile page

### ISSUE THREAD

**Issue by kanta1207** [nishiki-tech/nishiki-frontend#322]
## Description

Implement "Delete account" API client, which will be used in Profile page.

## Criteria

- [x] Implement "Delete user" API client
- [x] Apply the API client to Profile page

**Comment by nick-y-ito** [comment]
@kanta1207 
https://github.com/nishiki-tech/nishiki-backend/pull/318 seems to be already completed.
Could you please resume this task?

**Comment by kanta1207** [comment]
@nick-y-ito 
Thank you for notifying! I'll work on it 👍
