### ISSUE TITLE
Cannot copy an invitation link on mobiles and tablets

### ISSUE THREAD

**Issue by nick-y-ito** [nishiki-tech/nishiki-frontend#326]
## Description

Cannot copy an invitation link on mobiles and tablets, while it works on desktop. This issue happens both on iOS and Android.

## Notes

-

**Comment by ShoeheyOt** [comment]
It is not working with iPad, but there is no error message shown which should be if fail.
https://github.com/nishiki-tech/nishiki-frontend/assets/142355969/24987089-d8bc-4bc0-a765-14d74e864de3

**Comment by nick-y-ito** [comment]
This issue is going to be solved once https://github.com/nishiki-tech/nishiki-frontend/pull/339 is merged. I have deployed my test branch after merging the branch of that PR, and it worked correctly.
