### ISSUE TITLE
Loading state is required for each submit.

### ISSUE THREAD

**Issue by nick-y-ito** [nishiki-tech/nishiki-frontend#367]
## Description

Currently, multiple submissions are performed by tapping or clicking the submit button or mashing the [ enter/return ] key within a form.

## Criteria

- [x] Add the loading state (boolean), defaulting to `false`.
- [x] Turn it to `true` when submitting a form
- [x] Add an `if` statement inside every submit handler to exit the function and avoid multiple submissions.
- [x] Disable the submit button when the state is `true`

## Notes

- This task can be split into multiple smaller issues as needed

**Comment by arthathagary** [comment]
Hi,

I'm new to open-source contribution, and I'd like to work on this particular issue. I have some questions about the problem. After cloning the project and reviewing it, I'm wondering if I need to add a spinner near the button while submitting the form. If so, after submitting the form,  basic alert message triggered. I understand that the alert behavior may block the spinner animation. 

Is my understanding of the problem correct about adding loading spinners?

<img width="1440" alt="Screenshot 2024-03-16 at 7 54 04 PM" src="https://github.com/nishiki-tech/nishiki-frontend/assets/41929825/e05c1fb5-3e22-4481-bd3a-3aad326683d2">

**Comment by nick-y-ito** [comment]
@arthathagary 
Thank you for your interest :)

Honestly, we don't need the loading spinner for now because adding it affects the button size. Although we could add it to improve the UX, the main goal of this issue is only to avoid sending multiple API requests.

**Comment by arthathagary** [comment]
Ok, Now I understand the issue, can you assign this issue to me. I'll do this one 🤝

**Comment by nick-y-ito** [comment]
@arthathagary
Sure, I have done it　😊 I appreciate your contribution!

**Comment by nick-y-ito** [comment]
The criteria in the description are just suggestions. If you have better ideas, please feel free to provide alternatives.

**Comment by arthathagary** [comment]
Sure Man, 
I put a PR to this issue, check the PR if any changes you want tell me that i'll do that one 🤝
